<a href="https://colab.research.google.com/github/18cse169/aman18cse169/blob/main/Assignment_2_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr=[int(i) for i in input().split()]
arr=np.array(arr)
arr

6 5 9 7 2 4


array([6, 5, 9, 7, 2, 4])

In [3]:
print(np.__version__)

1.18.5


In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [8]:
#tuple to create array
arr=np.array((4,9,1,7))
arr

array([4, 9, 1, 7])

In [6]:
#create a 0-D array
a=np.array(10)
a

array(10)

In [9]:
#create a 1-D array
a=np.array([7,4,2,6,3])
a

array([7, 4, 2, 6, 3])

In [10]:
#create a 2-D array
a=np.array([[4,5,6],[7,8,9]])
print(a)

[[4 5 6]
 [7 8 9]]


In [11]:
#create a 3-D array
arr= np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [12]:
a=np.array(10)
b=np.array([1,2,3,4,5])
c=np.array([[1, 2, 3], [4, 5, 6]])
d=np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [13]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('print 3 rd element of 1stdim', arr[0, 3])

print 3 rd element of 1stdim 4


In [21]:
arr = np.array([[7, 4, 8, 1, 9], [5,2,10,3,6]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  6


In [18]:
arr = np.array([7, 4, 8, 1, 9, 2, 5])
print(arr[1:5:2])

[4 1]


In [17]:
arr = np.array(['bat', 'shoe', 'rope'])
print(arr.dtype)

<U4
